# Generated by Django 4.1.10 on 2023-07-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='massage',
            new_name='message',
        ),
    ]
