# Generated by Django 4.1.10 on 2023-07-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
