# Generated by Django 4.1.10 on 2023-07-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
