# Generated by Django 4.1.10 on 2023-07-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_link', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('sampler', models.CharField(blank=True, max_length=50, null=True)),
                ('cfg_scale', models.IntegerField(blank=True, null=True)),
                ('seed', models.CharField(blank=True, max_length=10, null=True)),
                ('model_hash', models.CharField(blank=True, max_length=20, null=True)),
                ('clip_skip', models.IntegerField(blank=True, null=True)),
                ('denoising_strength', models.CharField(blank=True, max_length=10, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('article_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img', to='articleapp.article')),
            ],
        ),
    ]
