# Generated by Django 4.1.10 on 2023-07-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_civitdata_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
